repos:


- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: "v0.11.8"
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix, --line-length, "121"]


- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-json
    - id: check-yaml
    - id: name-tests-test
      args: ['--django']
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: requirements-txt-fixer
    - id: check-added-large-files


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
